// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPmBnRC28AX1G4VPV3o6A41S9BY2kzCds',
    appId: '1:968213830986:web:613d437ba6b2c7dcf535b3',
    messagingSenderId: '968213830986',
    projectId: 'cosyncagreement',
    authDomain: 'cosyncagreement.firebaseapp.com',
    storageBucket: 'cosyncagreement.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4v8O8LUkoxFXwnC_xWyfko3n2Rqvnpg',
    appId: '1:968213830986:android:9de638b3fd92990bf535b3',
    messagingSenderId: '968213830986',
    projectId: 'cosyncagreement',
    storageBucket: 'cosyncagreement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAapoW-z4xpWe5DdiPyofkrNQ5RXPMuNMY',
    appId: '1:968213830986:ios:bde4ff19e708982df535b3',
    messagingSenderId: '968213830986',
    projectId: 'cosyncagreement',
    storageBucket: 'cosyncagreement.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemo',
  );
}
